# action.yml
name: "Hello World"
description: "Greet someone and record the time"
inputs:
  token: # id of input
    description: "Github Token"
    required: true
    default: ""
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.token }}   
